name: Node-hello CICD
on:
  push:
    branches:
          - master
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
  DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
  IMAGE_REPO_NAME: jagadeesh331/node-hello
jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      if: github.ref == 'refs/heads/master'
      run: |
         echo Logging in to Docker Hub...
         #docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
         echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
         echo Building the Docker image...
         docker build . --file Dockerfile --tag $IMAGE_REPO_NAME:${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
         echo Pushing the Docker image...
         docker push $IMAGE_REPO_NAME:${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER
         echo Pushed the Docker Image $IMAGE_REPO_NAME:${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER Successfully...
  Deploy:
    needs: BuildDockerImage
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Application In Environment
      if: github.ref == 'refs/heads/master'
      run: |
         git config --global user.name jagadeesh
         git config --global user.email jagadeeshdevops11@gmail.com
         git clone https://$DEPLOY_USER:$DEPLOY_PASS@github.com/jagadeesh-sre/node-charts.git
         git checkout main
         sed -i 's/^  tag':' .*$/  tag':'\ "'${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER'"/' values.yaml
         git stash
         git pull https://$DEPLOY_USER:$DEPLOY_PASS@github.com/jagadeesh-sre/node-charts.git
         git stash pop
         git commit -a -m "node-hello Docker Image Tag Updated to '${GITHUB_REF##*/}.$GITHUB_RUN_NUMBER'"
         git push https://$DEPLOY_USER:$DEPLOY_PASS@github.com/jagadeesh-sre/node-charts.git
         echo Updated Docker Image Tag On Helm...
